PROJECT/08_pjt/08_pjt/movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:movie_pk>/', views.detail, name='detail'),
    path('recommended/', views.recommended, name='recommended'),
]

PROJECT/08_pjt/08_pjt/mypjt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('community/', include('community.urls')),
    path('accounts/', include('accounts.urls')),
    path('movies/', include('movies.urls')),
]

PROJECT/08_pjt/08_pjt/movies/models.py
from django.db import models

class Genre(models.Model):
    name = models.CharField(max_length=50)

class Movie(models.Model):
    title = models.CharField(max_length=100)
    release_date = models.DateField()
    popularity = models.FloatField()
    vote_count = models.IntegerField()
    vote_average = models.FloatField()
    overview = models.TextField()
    poster_path = models.CharField(max_length=200)
    genres = models.ManyToManyField(Genre)

PROJECT/08_pjt/08_pjt/movies/forms.py
from django import forms

# Create your forms here.

PROJECT/08_pjt/08_pjt/movies/views.py
from django.shortcuts import render, get_list_or_404, get_object_or_404,redirect
from django.views.decorators.http import require_safe
from .models import Movie,Genre
from rest_framework import status
from rest_framework.response import Response
from rest_framework.decorators import api_view
from .serializer import MovieListSerializer,MovieDetailSerializer
from django.http import JsonResponse
from django.core import serializers

# Create your views here.
@require_safe
def index(request):
    if request.method == 'GET' :        
        movies = get_list_or_404(Movie)
        context = {
            'movies' : movies,
        }
        return render(request,'movies/index.html',context)
        

def detail(request, movie_pk):
  movie = Movie.objects.get(pk=movie_pk)
  genres = movie.genres.all()
  context = {
      'movie' : movie,
      'genres' : genres,
  }
  return render(request,'movies/detail.html',context)


@require_safe
def recommended(request):
    if request.user.is_authenticated:
        recommended_movies = []
        movies = Movie.objects.all()
        for movie in movies :
            if len(recommended_movies) == 10 :
                break
            
            if movie.vote_average > 8.5 :
                recommended_movies.append(movie)
        context = {
            'recommended_movies' : recommended_movies,
        }                        
        return render(request,'movies/recommended.html',context)
    return redirect('movies:index')

PROJECT/08_pjt/08_pjt/movies/templates/movies/detail.html
{% extends 'base.html' %}

{% block content %}
    <p>제목 : {{movie.title}}</p>
    <p>개봉 : {{movie.release_date}}</p>
    <p>popularity : {{movie.popularity}}</p>
    <p>투표 : {{movie.vote_count}}</p>
    <p>평점 : {{movie.vote_average}}</p>
    <p>줄거리 : {{movie.overview}}</p>
    <p>장르 :
    {% for genre in genres %}
        {{genre.name}}
    {% endfor %}
    <p><a href="{% url 'movies:recommended' %}">비슷한 장르의 영화 추천</a></p>
    </p>
    <img src="{{movie.poster_path}}" alt="">
{% endblock %}

PROJECT/08_pjt/08_pjt/movies/templates/movies/index.html
{% extends 'base.html' %}

{% block content %}
  <h1>Movies</h1>
  <hr>
  {% for movie in movies %}
    <a href="{% url 'movies:detail' movie.pk %}">{{movie.title}}</a>
    <p>평점 : 
            {% if movie.vote_average > 8.7 %}
            ★★★★★
            {% elif movie.vote_average > 8.5 %}
            ★★★★
            {% elif movie.vote_average > 8.2 %}
            ★★★
            {% else %}
            ★★
            {% endif %}
    </p>
    <hr>
  {% endfor %}
{% endblock %}

PROJECT/08_pjt/08_pjt/movies/templates/movies/recommended.html
{% extends 'base.html' %}

{% block content %}
    
        {% for movie in recommended_movies %}
        <div>
            <p style="text-align: center;"><a href="{% url 'movies:detail' movie.pk %}">{{movie.title}}</a></p>
            {% if movie.vote_average > 8.7 %}
            <p style="text-align: center;">★★★★★</p>
            {% elif movie.vote_average > 8.5 %}
            <p style="text-align: center;">★★★★</p>
            {% elif movie.vote_average > 8.2 %}
            <p style="text-align: center;">★★★</p>
            {% endif %}
            <p style="text-align: center;"><img src="{{movie.poster_path}}" alt=""></p>
            <br>
            <p>{{movie.overview}}</p>
            <hr>
        </div>
        {% endfor %}

{% endblock content %}